const cities=[['Budapest',47.4979,19.0402],['Debrecen',47.5316,21.6273],['Szeged',46.2530,20.1414],['Pécs',46.0727,18.2323],['Győr',47.6875,17.6504],['Miskolc',48.1035,20.7784],['Nyíregyháza',47.9554,21.7167],['Kecskemét',46.8964,19.6897],['Székesfehérvár',47.1860,18.4221],['Szolnok',47.1621,20.1825],['Sopron',47.6817,16.5845],['Eger',47.9025,20.3772],['Kaposvár',46.3594,17.7968],['Zalaegerszeg',46.8417,16.8416],['Veszprém',47.0929,17.9133],['Tatabánya',47.5862,18.3940],['Békéscsaba',46.6736,21.0877],['Szombathely',47.2307,16.6218],['Salgótarján',48.0935,19.7999],['Dunaújváros',46.9619,18.9355]].map(([name,lat,lon])=>({name,lat,lon}));
const map=document.getElementById('map'),click=document.getElementById('map-click'),guessLayer=document.getElementById('guess-layer');
const cityEl=document.getElementById('city-name'),attemptEl=document.getElementById('attempt'),scoreEl=document.getElementById('score'),result=document.getElementById('result'),nextBtn=document.getElementById('next'),newBtn=document.getElementById('new-game');
const directionBox=document.getElementById('direction-box'),normalBtn=document.getElementById('normal-mode'),reliefBtn=document.getElementById('relief-mode');
let target,attempt,score,used=[];
const bounds={minLon:16.05,maxLon:22.95,minLat:45.7,maxLat:48.65};
function distanceKm(a,b){const R=6371,p=Math.PI/180,dLat=(b.lat-a.lat)*p,dLon=(b.lon-a.lon)*p,x=Math.sin(dLat/2)**2+Math.cos(a.lat*p)*Math.cos(b.lat*p)*Math.sin(dLon/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function bearing(a,b){const p=Math.PI/180,y=Math.sin((b.lon-a.lon)*p)*Math.cos(b.lat*p),x=Math.cos(a.lat*p)*Math.sin(b.lat*p)-Math.sin(a.lat*p)*Math.cos(b.lat*p)*Math.cos((b.lon-a.lon)*p);return(Math.atan2(y,x)*180/Math.PI+360)%360}
function direction(deg){const d=[['É','↑'],['ÉK','↗'],['K','→'],['DK','↘'],['D','↓'],['DNy','↙'],['Ny','←'],['ÉNy','↖']];return d[Math.round(deg/45)%8]}
function start(){score=0;used=[];scoreEl.textContent=0;newRound()}
function newRound(){attempt=0;nextBtn.disabled=true;result.innerHTML='';guessLayer.innerHTML='';directionBox.innerHTML='<span class="dir-arrow">—</span><span class="dir-text">Tippelj a térképen</span>';const pool=cities.filter(c=>!used.includes(c.name));if(!pool.length){finish();return}target=pool[Math.floor(Math.random()*pool.length)];used.push(target.name);cityEl.textContent=target.name;attemptEl.textContent=1}
function finish(){cityEl.textContent='Játék vége!';attemptEl.textContent='–';result.innerHTML=`<div class="big ok">🎉 Végeredmény: ${score} pont</div><div class="info">Mind a ${used.length} várost végigjátszottad.</div>`;nextBtn.disabled=true;directionBox.innerHTML='<span class="dir-arrow">🏁</span><span class="dir-text">Vége</span>'}
function setMode(relief){map.classList.toggle('relief-mode',relief);normalBtn.classList.toggle('active',!relief);reliefBtn.classList.toggle('active',relief)}
function placeGuess(x,y){const m=document.createElement('span');m.className='guess-marker';m.style.left=`${x*100}%`;m.style.top=`${y*100}%`;guessLayer.appendChild(m)}
click.addEventListener('click',e=>{if(attempt>=3||!target)return;const r=click.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;const lon=bounds.minLon+x*(bounds.maxLon-bounds.minLon),lat=bounds.maxLat-y*(bounds.maxLat-bounds.minLat),guess={lat,lon};const d=distanceKm(guess,target),b=bearing(guess,target);attempt++;attemptEl.textContent=Math.min(attempt+1,3);placeGuess(x,y);const [dir,arrow]=direction(b);directionBox.innerHTML=`<span class="dir-arrow">${arrow}</span><span class="dir-text">${dir} • ${d.toFixed(1)} km</span>`;const points=d<=5?100:d<=15?75:d<=20?50:d<=40?25:0;score+=points;scoreEl.textContent=score;if(d<=20){result.innerHTML=`<div class="big ok">🎯 Talált! ${d.toFixed(1)} km-re voltál.</div><div class="info">+${points} pont • A következő városra léphetsz.</div>`;nextBtn.disabled=false;attempt=3}else if(attempt>=3){result.innerHTML=`<div class="big bad">❌ Most nem sikerült.</div><div class="info">3 próbálkozásból nem sikerült 20 km-en belülre kerülni.</div>`;nextBtn.disabled=false;attempt=3}else{result.innerHTML=`<div class="big">📏 ${d.toFixed(1)} km</div><div class="info">A keresett város <b>${dir}</b> irányban van. Még ${3-attempt} próbálkozásod maradt.</div>`}});
nextBtn.addEventListener('click',newRound);newBtn.addEventListener('click',start);normalBtn.addEventListener('click',()=>setMode(false));reliefBtn.addEventListener('click',()=>setMode(true));setMode(false);start();