const cities=[['Budapest',47.4979,19.0402],['Debrecen',47.5316,21.6273],['Szeged',46.2530,20.1414],['Pécs',46.0727,18.2323],['Győr',47.6875,17.6504],['Miskolc',48.1035,20.7784],['Nyíregyháza',47.9554,21.7167],['Kecskemét',46.8964,19.6897],['Székesfehérvár',47.1860,18.4221],['Szolnok',47.1621,20.1825],['Sopron',47.6817,16.5845],['Eger',47.9025,20.3772],['Kaposvár',46.3594,17.7968],['Zalaegerszeg',46.8417,16.8416],['Veszprém',47.0929,17.9133],['Tatabánya',47.5862,18.3940],['Békéscsaba',46.6736,21.0877],['Szombathely',47.2307,16.6218],['Salgótarján',48.0935,19.7999],['Dunaújváros',46.9619,18.9355]].map(([name,lat,lon])=>({name,lat,lon}));
const map=document.getElementById('map'),content=document.getElementById('map-content'),click=document.getElementById('map-click'),guessLayer=document.getElementById('guess-layer');
const cityEl=document.getElementById('city-name'),attemptEl=document.getElementById('attempt'),scoreEl=document.getElementById('score'),result=document.getElementById('result'),nextBtn=document.getElementById('next'),newBtn=document.getElementById('new-game');
const directionBox=document.getElementById('direction-box'),normalBtn=document.getElementById('normal-mode'),reliefBtn=document.getElementById('relief-mode');
const zoomIn=document.getElementById('zoom-in'),zoomOut=document.getElementById('zoom-out'),zoomReset=document.getElementById('zoom-reset');
let target,attempt,score,used=[];let zoom=1,panX=0,panY=0;let pointers=new Map(),dragStart=null,pinchStart=null,moved=false;
const bounds={minLon:16.05,maxLon:22.95,minLat:45.7,maxLat:48.65};
function distanceKm(a,b){const R=6371,p=Math.PI/180,dLat=(b.lat-a.lat)*p,dLon=(b.lon-a.lon)*p,x=Math.sin(dLat/2)**2+Math.cos(a.lat*p)*Math.cos(b.lat*p)*Math.sin(dLon/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function bearing(a,b){const p=Math.PI/180,y=Math.sin((b.lon-a.lon)*p)*Math.cos(b.lat*p),x=Math.cos(a.lat*p)*Math.sin(b.lat*p)-Math.sin(a.lat*p)*Math.cos(b.lat*p)*Math.cos((b.lon-a.lon)*p);return(Math.atan2(y,x)*180/Math.PI+360)%360}
function direction(deg){const d=[['É','↑'],['ÉK','↗'],['K','→'],['DK','↘'],['D','↓'],['DNy','↙'],['Ny','←'],['ÉNy','↖']];return d[Math.round(deg/45)%8]}
function clampPan(){const r=map.getBoundingClientRect(),maxX=Math.max(0,r.width*(zoom-1)),maxY=Math.max(0,r.height*(zoom-1));panX=Math.max(-maxX,Math.min(0,panX));panY=Math.max(-maxY,Math.min(0,panY))}
function applyTransform(){clampPan();content.style.transform=`translate(${panX}px,${panY}px) scale(${zoom})`;zoomReset.textContent=`${Math.round(zoom*100)}%`}
function setZoom(next,cx=.5,cy=.5){const old=zoom;zoom=Math.max(1,Math.min(3,next));if(zoom===old)return;const r=map.getBoundingClientRect(),x=r.width*cx,y=r.height*cy;panX=x-(x-panX)*(zoom/old);panY=y-(y-panY)*(zoom/old);applyTransform()}
function resetView(){zoom=1;panX=0;panY=0;applyTransform()}
function start(){score=0;used=[];scoreEl.textContent=0;newRound()}
function newRound(){attempt=0;nextBtn.disabled=true;result.innerHTML='';guessLayer.innerHTML='';directionBox.innerHTML='<span class="dir-arrow">—</span><span class="dir-text">Tippelj a térképen</span>';resetView();const pool=cities.filter(c=>!used.includes(c.name));if(!pool.length){finish();return}target=pool[Math.floor(Math.random()*pool.length)];used.push(target.name);cityEl.textContent=target.name;attemptEl.textContent=1}
function finish(){cityEl.textContent='Játék vége!';attemptEl.textContent='–';result.innerHTML=`<div class="big ok">🎉 Végeredmény: ${score} pont</div><div class="info">Mind a ${used.length} várost végigjátszottad.</div>`;nextBtn.disabled=true;directionBox.innerHTML='<span class="dir-arrow">🏁</span><span class="dir-text">Vége</span>'}
function setMode(relief){map.classList.toggle('relief-mode',relief);normalBtn.classList.toggle('active',!relief);reliefBtn.classList.toggle('active',relief)}
function placeGuess(x,y){const m=document.createElement('span');m.className='guess-marker';m.style.left=`${x*100}%`;m.style.top=`${y*100}%`;guessLayer.appendChild(m)}
function submitGuess(clientX,clientY){if(attempt>=3||!target)return;const r=map.getBoundingClientRect();const sx=(clientX-r.left-panX)/(r.width*zoom),sy=(clientY-r.top-panY)/(r.height*zoom);if(sx<0||sx>1||sy<0||sy>1)return;const lon=bounds.minLon+sx*(bounds.maxLon-bounds.minLon),lat=bounds.maxLat-sy*(bounds.maxLat-bounds.minLat),guess={lat,lon};const d=distanceKm(guess,target),b=bearing(guess,target);attempt++;attemptEl.textContent=Math.min(attempt+1,3);placeGuess(sx,sy);const [dir,arrow]=direction(b);directionBox.innerHTML=`<span class="dir-arrow">${arrow}</span><span class="dir-text">${dir} • ${d.toFixed(1)} km</span>`;const points=d<=5?100:d<=15?75:d<=20?50:d<=40?25:0;score+=points;scoreEl.textContent=score;if(d<=20){result.innerHTML=`<div class="big ok">🎯 Talált! ${d.toFixed(1)} km-re voltál.</div><div class="info">+${points} pont • A következő városra léphetsz.</div>`;nextBtn.disabled=false;attempt=3}else if(attempt>=3){result.innerHTML=`<div class="big bad">❌ Most nem sikerült.</div><div class="info">3 próbálkozásból nem sikerült 20 km-en belülre kerülni.</div>`;nextBtn.disabled=false;attempt=3}else{result.innerHTML=`<div class="big">📏 ${d.toFixed(1)} km</div><div class="info">A keresett város <b>${dir}</b> irányban van. Még ${3-attempt} próbálkozásod maradt.</div>`}}
function pos(e){const r=map.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
click.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;e.preventDefault();click.setPointerCapture?.(e.pointerId);const p=pos(e);pointers.set(e.pointerId,p);moved=false;if(pointers.size===1)dragStart={pointer:p,panX,panY};else if(pointers.size===2){const [a,b]=[...pointers.values()];pinchStart={distance:dist(a,b),zoom,panX,panY,center:{x:(a.x+b.x)/2,y:(a.y+b.y)/2}};dragStart=null;}});
click.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;e.preventDefault();const p=pos(e);pointers.set(e.pointerId,p);if(pointers.size===1&&dragStart){const dx=p.x-dragStart.pointer.x,dy=p.y-dragStart.pointer.y;if(Math.hypot(dx,dy)>5)moved=true;if(zoom>1){panX=dragStart.panX+dx;panY=dragStart.panY+dy;applyTransform();}}else if(pointers.size===2&&pinchStart){const [a,b]=[...pointers.values()];const d=dist(a,b);if(Math.abs(d-pinchStart.distance)>3)moved=true;const old=zoom;zoom=Math.max(1,Math.min(3,pinchStart.zoom*d/pinchStart.distance));const r=map.getBoundingClientRect(),cx=pinchStart.center.x/r.width,cy=pinchStart.center.y/r.height;panX=pinchStart.center.x-(pinchStart.center.x-pinchStart.panX)*(zoom/old);panY=pinchStart.center.y-(pinchStart.center.y-pinchStart.panY)*(zoom/old);applyTransform();}});
click.addEventListener('pointerup',e=>{const wasMoved=moved;const p=pos(e);pointers.delete(e.pointerId);click.releasePointerCapture?.(e.pointerId);if(pointers.size===0){if(!wasMoved&&dragStart)submitGuess(e.clientX,e.clientY);dragStart=null;pinchStart=null;}else if(pointers.size===1){const remaining=[...pointers.values()][0];dragStart={pointer:remaining,panX,panY};}});
click.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);dragStart=null;pinchStart=null;moved=true});
click.addEventListener('wheel',e=>{e.preventDefault();const r=map.getBoundingClientRect(),cx=(e.clientX-r.left)/r.width,cy=(e.clientY-r.top)/r.height;setZoom(zoom+(e.deltaY<0?.25:-.25),cx,cy)},{passive:false});
zoomIn.addEventListener('click',()=>setZoom(zoom+.25));zoomOut.addEventListener('click',()=>setZoom(zoom-.25));zoomReset.addEventListener('click',resetView);nextBtn.addEventListener('click',newRound);newBtn.addEventListener('click',start);normalBtn.addEventListener('click',()=>setMode(false));reliefBtn.addEventListener('click',()=>setMode(true));setMode(false);applyTransform();start();
